linters:
  enable:
    # Basic linters
    - errcheck        # Check for unchecked errors
    - gosimple        # Simplify code
    - govet           # Examine Go source code for suspicious constructs
    - ineffassign     # Detect unused assignments
    - staticcheck     # Go static analysis tool
    - typecheck       # Type-check Go code
    - unused          # Check for unused constants, variables, functions and types
    
    # Code quality linters
    - bodyclose       # Check whether HTTP response bodies are closed
    - dupl            # Find code clones
    - durationcheck   # Check for time.Duration misuse
    - errorlint       # Find errors handling issues
    - exhaustive      # Check exhaustiveness of enum switch statements
    - gocognit        # Calculate cognitive complexity
    - goconst         # Find repeated strings that could be constants
    - gocritic        # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo         # Calculate cyclomatic complexity
    - godot           # Check if comments end with a period
    - gofmt           # Check if code was gofmt-ed
    - goimports       # Check imports formatting
    - gosec           # Inspects source code for security problems
    - misspell        # Find commonly misspelled English words
    - nakedret        # Find naked returns
    - nolintlint      # Reports ill-formed or insufficient nolint directives
    - prealloc        # Find slice declarations that could potentially be preallocated
    - revive          # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - stylecheck      # Replacement for golint
    - thelper         # Detect t.Helper() calls in test helpers
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Find unused function parameters
    - whitespace      # Tool for detection of leading and trailing whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G104 # Audit errors not checked (already covered by errcheck)
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - examples
